name: contagiograms
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - brotlipy=0.7.0
  - ca-certificates=2020.6.24
  - certifi=2020.6.20
  - cffi=1.14.0
  - chardet=3.0.4
  - cryptography=2.9.2
  - cycler=0.10.0
  - dbus=1.13.16
  - expat=2.2.9
  - fontconfig=2.13.0
  - freetype=2.10.2
  - glib=2.65.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=2.10
  - intel-openmp=2020.1
  - jpeg=9b
  - kiwisolver=1.2.0
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.10
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - numpy=1.18.5
  - numpy-base=1.18.5
  - openssl=1.1.1g
  - pandas=1.0.5
  - pcre=8.44
  - pip=20.1.1
  - pycparser=2.20
  - pymongo=3.9.0
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.8.3
  - python-bidi=0.4.2
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2020.1
  - qt=5.9.7
  - readline=8.0
  - requests=2.24.0
  - setuptools=49.2.0
  - sip=4.19.13
  - six=1.15.0
  - sqlite=3.32.3
  - tk=8.6.10
  - tornado=6.0.4
  - urllib3=1.25.9
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11

