"""
Contagiograms
Copyright (c) 2020 The Computational Story Lab.
Licensed under the MIT License;
"""

import re
import matplotlib.font_manager as fm

types_colors = {
    'AT': 'dimgrey',
    'RT': 'darkorange',
    'OT': 'steelblue',
}


fm._rebuild()
#noto = [f.name for f in fm.fontManager.ttflist if 'Noto Sans' in f.name]
fonts = {
    'Default': fm.FontProperties(family=["sans-serif"]),
    'Korean': fm.FontProperties(family=["Noto Sans CJK KR", "Noto Sans CJK", "sans-serif"]),
    'Tamil': fm.FontProperties(family=["Noto Sans Tamil", "sans-serif"]),
}

contagiograms = dict(
    example=[
        ('kevät', 'fi'), ('Carnaval', 'pt'),
        ('Lionel Messi', 'es'), ('#TGIF', 'en'),
        ('virus', 'fr'), ('Brexit', 'de')
    ],
    langs=[
        ('❤', 'en'), ('Resurrección', 'es'), ('?', 'und'),
        ('eleição', 'pt'), ('ثورة', 'ar'), ('@bts_twt', 'ko'),
        ('Flüchtling', 'de'), ('San Valentino', 'it'), ('карантин', 'ru'),
    ],
)

loi = [
    "en", "ja", "und", "es",
    "pt", "ar", "th", "ko",
    "fr", "tr", "de", "it",
]

supported_languages = {
    'af': 'Afrikaans',
    'als': 'Tosk-Albanian',
    'am': 'Amharic',
    'an': 'Aragonese',
    'ar': 'Arabic',
    'arz': 'Egyptian-Arabic',
    'as': 'Assamese',
    'ast': 'Asturian',
    'av': 'Avaric',
    'az': 'Azerbaijani',
    'azb': 'South-Azerbaijani',
    'ba': 'Bashkir',
    'bar': 'Bavarian',
    'bcl': 'Central-Bikol',
    'be': 'Belarusian',
    'bg': 'Bulgarian',
    'bh': 'Bihari',
    'bn': 'Bengali',
    'bo': 'Tibetan',
    'bpy': 'Bishnupriya',
    'br': 'Breton',
    'bs': 'Bosnian',
    'bxr': 'Russian-Buriat',
    'ca': 'Catalan',
    'cbk': 'Chavacano',
    'ce': 'Chechen',
    'ceb': 'Cebuano',
    'ckb': 'Central-Kurdish',
    'co': 'Corsican',
    'cs': 'Czech',
    'cv': 'Chuvash',
    'cy': 'Welsh',
    'da': 'Danish',
    'de': 'German',
    'diq': 'Dimli',
    'dsb': 'Lower-Sorbian',
    'dty': 'Dotyali',
    'dv': 'Divehi',
    'el': 'Greek',
    'eml': 'Emiliano-Romagnolo',
    'en': 'English',
    'eo': 'Esperanto',
    'es': 'Spanish',
    'et': 'Estonian',
    'eu': 'Basque',
    'fa': 'Persian',
    'fi': 'Finnish',
    'fr': 'French',
    'frr': 'Northen-Frisian',
    'fy': 'Frisian',
    'ga': 'Irish',
    'gd': 'Gaelic',
    'gl': 'Gallegan',
    'gn': 'Guarani',
    'gom': 'Goan-Konkani',
    'gu': 'Gujarati',
    'gv': 'Manx',
    'he': 'Hebrew',
    'hi': 'Hindi',
    'hif': 'Fiji-Hindi',
    'hr': 'Croatian',
    'hsb': 'Upper-Sorbian',
    'ht': 'Haitian',
    'hu': 'Hungarian',
    'hy': 'Armenian',
    'ia': 'Interlingua',
    'id': 'Indonesian',
    'ie': 'Interlingue',
    'ilo': 'Iloko',
    'io': 'Ido',
    'is': 'Icelandic',
    'it': 'Italian',
    'ja': 'Japanese',
    'jbo': 'Lojban',
    'jv': 'Javanese',
    'ka': 'Georgian',
    'kk': 'Kazakh',
    'km': 'Khmer',
    'kn': 'Kannada',
    'ko': 'Korean',
    'krc': 'Karachay-Balkar',
    'ku': 'Kurdish',
    'kv': 'Komi',
    'kw': 'Cornish',
    'ky': 'Kirghiz',
    'la': 'Latin',
    'lb': 'Luxembourgish',
    'lez': 'Lezghian',
    'li': 'Limburgan',
    'lmo': 'Lombard',
    'lo': 'Lao',
    'lrc': 'Northern-Luri',
    'lt': 'Lithuanian',
    'lv': 'Latvian',
    'mai': 'Maithili',
    'mg': 'Malagasy',
    'mhr': 'Eastern-Mari',
    'min': 'Minangkabau',
    'mk': 'Macedonian',
    'ml': 'Malayalam',
    'mn': 'Mongolian',
    'mr': 'Marathi',
    'mrj': 'Western-Mari',
    'ms': 'Malay',
    'mt': 'Maltese',
    'mwl': 'Mirandese',
    'my': 'Burmese',
    'myv': 'Erzya',
    'mzn': 'Mazanderani',
    'nah': 'Nahuatl',
    'nap': 'Neapolitan',
    'nds': 'Saxon',
    'ne': 'Nepali',
    'new': 'Newari',
    'nl': 'Dutch',
    'nn': 'Nynorsk',
    'no': 'Norwegian',
    'oc': 'Occitan',
    'or': 'Oriya',
    'os': 'Ossetic',
    'pa': 'Panjabi',
    'pam': 'Pampanga',
    'pfl': 'Pfaelzisch',
    'pl': 'Polish',
    'pms': 'Piemontese',
    'pnb': 'Western-Panjabi',
    'ps': 'Pushto',
    'pt': 'Portuguese',
    'qu': 'Quechua',
    'rm': 'Raeto-Romance',
    'ro': 'Romanian',
    'ru': 'Russian',
    'rue': 'Rusyn',
    'sa': 'Sanskrit',
    'sah': 'Yakut',
    'sc': 'Sardinian',
    'scn': 'Sicilian',
    'sco': 'Scots',
    'sd': 'Sindhi',
    'sh': 'Serbo-Croatian',
    'si': 'Sinhala',
    'sk': 'Slovak',
    'sl': 'Slovenian',
    'so': 'Somali',
    'sq': 'Albanian',
    'sr': 'Serbian',
    'su': 'Sundanese',
    'sv': 'Swedish',
    'sw': 'Swahili',
    'ta': 'Tamil',
    'te': 'Telugu',
    'tg': 'Tajik',
    'th': 'Thai',
    'tk': 'Turkmen',
    'tl': 'Tagalog',
    'tr': 'Turkish',
    'tt': 'Tatar',
    'tyv': 'Tuvinian',
    'ug': 'Uighur',
    'uk': 'Ukrainian',
    'und': 'Undefined',
    'unknown': 'Unknown',
    'ur': 'Urdu',
    'uz': 'Uzbek',
    'vec': 'Venetian',
    'vep': 'Veps',
    'vi': 'Vietnamese',
    'vls': 'Vlaams',
    'vo': 'Volapük',
    'wa': 'Walloon',
    'war': 'Waray',
    'wuu': 'Wu-Chinese',
    'xal': 'Kalmyk',
    'xmf': 'Mingrelian',
    'yi': 'Yiddish',
    'yo': 'Yoruba',
    'yue': 'Yue-Chinese',
    'zh': 'Chinese'
 }


ngrams_parser = re.compile(
    r"(([🇦-🇿]{2})|(㊙|㊗|〽|〰|⭕|⭐|[⬛-⬜]|[⬅-⬇]|[⤴-⤵]|➿|➰|➡|[➕-➗]|[❣-❧]|[❣-❤]|❗|[❓-❕]|❎|❌|❇|❄|[✳-✴]|✨|✡|✝|✖|✔|✒|✏|[✌-✒]|[✌-✍]|[✊-✋]|[✈-✉]|✅|✂|[✁-✄]|✀|⛽|⛺|⛹|[⛷-⛺]|⛵|[⛲-⛳]|[⛰-⛵]|⛪|[⛩-⛪]|[⛨-⛿]|[⛤-⛧]|⛣|⛢|⛔|[⛓-⛔]|⛑|[⛏-⛡]|⛏|⛎|⛈|[⛄-⛍]|[⛄-⛅]|[⛀-⛃]|[⚽-⚿]|[⚽-⚾]|[⚳-⚼]|⚲|[⚰-⚱]|[⚪-⚫]|[⚢-⚱]|⚡|[⚠-⚡]|[⚞-⚟]|⚝|[⚛-⚜]|⚙|⚓|[⚒-⚜]|[⚒-⚗]|[⚐-⚑]|[⚀-⚅]|♿|[♾-♿]|♻|[♲-♽]|[♰-♱]|♨|[♥-♦]|♣|[♟-♠]|[♈-♓]|♂|♀|[☸-☺]|[☮-☯]|☪|☦|[☢-☣]|☠|☝|[☚-♯]|☙|☘|[☖-☗]|[☔-☕]|☑|☎|[☇-☒]|[☀-★]|[☀-☄]|[◽-◾]|[◻-◾]|◀|▶|[▪-▫]|Ⓜ|[⏸-⏺]|⏳|⏰|[⏩-⏳]|[⏩-⏬]|⏏|⎈|⌨|[⌚-⌛]|[↩-↪]|[↔-↙]|ℹ|™|⁉|‼|[🪖-🿽]|[🪐-🪕]|[🪃-🪏]|[🪀-🪂]|[🩻-🩿]|[🩸-🩺]|[🩴-🩷]|[🩰-🩳]|[🩮-🩯]|[🩠-🩭]|[🩔-🩟]|[🨀-🩓]|[🧧-🧿]|[🧑-🧝]|[🧐-🧦]|[🧍-🧏]|[🧋-🧌]|[🧃-🧊]|[🧁-🧂]|🧀|🦻|[🦺-🦿]|[🦸-🦹]|[🦵-🦶]|[🦰-🦹]|[🦮-🦯]|[🦫-🦭]|[🦥-🦪]|[🦣-🦤]|[🦘-🦢]|[🦒-🦗]|[🦅-🦑]|[🦀-🦄]|[🥼-🥿]|🥻|🥺|[🥷-🥹]|[🥳-🥶]|🥲|🥱|[🥬-🥰]|[🥟-🥫]|[🥐-🥞]|[🥍-🥏]|🥌|[🥇-🥋]|[🥀-🥅]|🤿|[🤼-🤾]|[🤳-🤺]|[🤳-🤹]|[🤱-🤲]|🤰|[🤨-🤯]|🤦|[🤠-🤧]|🤟|[🤙-🤞]|🤘|[🤐-🤘]|🤏|[🤍-🤏]|🤌|[🢮-🣿]|[🢈-🢏]|[🡚-🡟]|[🡈-🡏]|[🠌-🠏]|[🟬-🟿]|[🟠-🟫]|[🟙-🟟]|[🟕-🟘]|[🝴-🝿]|[🛻-🛿]|🛺|🛹|[🛷-🛸]|[🛴-🛶]|🛳|[🛰-🛳]|🛰|[🛭-🛯]|[🛫-🛬]|🛩|[🛠-🛬]|[🛠-🛥]|[🛖-🛟]|🛕|[🛓-🛔]|[🛑-🛒]|🛐|🛌|[🛋-🛏]|[🛆-🛏]|🛀|[🚴-🚶]|🚣|[🚀-🛅]|[🙋-🙏]|[🙅-🙏]|[🙅-🙇]|[🙃-🙄]|[🙁-🙂]|[😵-🙀]|😴|[😰-😳]|[😮-😯]|😭|😬|[😨-😫]|[😦-😧]|[😠-😥]|😟|[😜-😞]|😛|😚|😙|😘|😗|😖|😕|[😒-😔]|😑|[😁-😐]|😀|[🗻-🗿]|🗺|🗳|🗯|🗨|🗣|🗡|[🗜-🗞]|[🗑-🗓]|[🗂-🗄]|🖼|[🖱-🖲]|🖨|[🖥-🗺]|🖥|🖤|[🖕-🖖]|🖐|[🖊-🖍]|🖇|[🕻-🖣]|🕺|[🕴-🕵]|[🕳-🕹]|[🕯-🕰]|[🕨-🕹]|[🕐-🕧]|[🕋-🕏]|[🕋-🕎]|[🕉-🕊]|[🕆-🕊]|[🔀-🔽]|📿|[📽-📾]|📽|[📹-📼]|📸|💪|💑|💏|[💅-💇]|[💁-💃]|👼|[👦-👸]|[👆-👐]|[👂-📷]|[👂-👃]|👁|👀|🐿|[🐀-🐾]|[🏸-🏿]|[🏸-🏺]|🏷|🏴|[🏳-🏵]|[🏱-🏷]|[🏠-🏰]|[🏔-🏟]|[🏏-🏓]|[🏋-🏎]|[🏋-🏌]|🏊|🏇|[🏆-🏊]|🏅|[🏂-🏄]|[🎠-🏄]|[🎞-🎟]|[🎙-🎛]|[🎖-🎗]|[🎔-🎟]|🎅|[🎀-🎓]|[🍾-🍿]|🍽|[🌷-🍼]|🌶|[🌰-🌵]|[🌭-🌯]|[🌤-🌬]|[🌡-🌬]|🌡|[🌀-🌠]|[🉦-🋿]|[🉠-🉥]|[🉒-🉟]|[🉐-🉑]|[🉉-🉏]|[🈼-🈿]|[🈸-🈺]|[🈲-🈺]|[🈲-🈶]|🈯|🈚|[🈃-🈏]|[🈁-🈂]|🈁|[🇦-🇿]|[🆭-🇥]|[🆑-🆚]|🆎|🅿|🅾|[🅰-🅱]|[🅭-🅯]|🅬|🄯|[🄍-🄏]|[🃶-🃿]|[🃠-🃵]|[🃑-🃟]|🃐|🃏|[🃁-🃏]|🃀|🂿|[🂱-🂾]|[🂯-🂰]|[🂠-🂮]|[🂔-🂟]|[🀰-🂓]|[🀬-🀯]|🀄|[🀀-🀫])([🏻-🏿]?‍?[🦰-🦳]?)|(&\S+;)|(https?:\/\/\w+\.\S+)|((?:\b|[@\#\$\£\¥\¢]|[\u20a0-\u20cf])[\u20a0-\u20cf\$\£\¥\¢\w\@\.\#\‘\’\'\&\:\,\]\*\-\/\[\=]+([\'\']|\b))|([\-\.]+)|(\S))"
)
